name: Android CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug
      - name: Ensure Folder Structure
        run: mkdir -p build/outputs/apk/debug/

      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/

      - name: Create ZIP file
        run: zip -r debug-apk.zip app/build/outputs/apk/debug/

      - name: Notify Teams Channel
        if: success()
        run: |
          echo "Sending release notification to Teams channel..."
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "New release available: ${{ env.date_today }} - ${{ env.repository_name }}",
            "sections": [
              {
                "activityTitle": "Release Details",
                "facts": [
                  {
                    "name": "Repository",
                    "value": "${{ env.repository_name }}"
                  },
                  {
                    "name": "Date",
                    "value": "${{ env.date_today }}"
                  }
                ]
              }
            ],
            "attachments": [
              {
                "contentType": "application/zip",
                "contentUrl": "data:application/zip;base64,$(base64 -w 0 debug-apk.zip)",
                "name": "debug-apk.zip"
              }
            ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
