name: Android CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: List files in output directory (for debugging)
        run: ls -la app/build/outputs/apk/debug/  # Use this to verify APK presence

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk  # Ensure correct path

      - name: Get artifact download URL (with error handling)
        id: artifact-url
        run: |
          set +e
          ARTIFACT_URL=$(jq -r '.artifacts[0].archive_download_url' < "${GITHUB_EVENT_PATH}")
          if [[ -z $ARTIFACT_URL ]]; then
            echo "Error: Artifact download URL not found."
            exit 1
          fi
          echo "::set-output name=apk_download_url::$ARTIFACT_URL"

      - name: Notify Teams Channel (with direct download link)
        if: success()
        run: |
          echo "Sending release notification to Teams channel..."
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "New release available: ${{ env.date_today }} - ${{ env.repository_name }}",
            "sections": [
              {
                "activityTitle": "Release Details",
                "facts": [
                  {
                    "name": "Repository",
                    "value": "${{ env.repository_name }}"
                  },
                  {
                    "name": "Date",
                    "value": "${{ env.date_today }}"
                  }
                ]
              }
            ],
            "potentialAction": [
              {
                "@context": "http://schema.org",
                "@type": "ViewAction",
                "name": "Download APK",
                "target": ["${{ steps.artifact-url.outputs.apk_download_url }}"]
              }
            ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
